#cloud-config

users:
  - name: ubuntu
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINZQDiJGOySc8rzjywPViE7Z6/VDgb3RFgXzeS3AdByC m183-burren-tbz

packages:
  - docker.io

runcmd:
  - systemctl start docker
  - systemctl enable docker